# Name of the GitHub Action
name: Build scipion-em-xmipp on Pull Request

# Specify when the Action should be triggered: when a pull request is opened against the 'devel' or 'master' branch
on:
  pull_request:
    branches: [devel, master]

# Define the job that should be run
jobs:
  build:
    # Specify the machine to run the job on
    runs-on: ubuntu-20.04

    # Define the steps to be taken in the job
    steps:
    # Getting current test time
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+02:00"
    
    # Using current time to view test time (for debugging purposes)
    - name: Use current time
      env:
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      run: echo $R_TIME
    
    #Installing CUDA
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
        linux-local-args: '[ "--toolkit" ]'

    - run: echo "Installed cuda version is:${{steps.cuda-toolkit.outputs.cuda}}"

    # Installing Miniconda
    - name: Install Miniconda
      working-directory: ${{ github.workspace }}/../
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
        bash Miniconda3-latest-Linux-x86_64.sh -b -p ${{ github.workspace }}/../miniconda/ && \
        source ./miniconda/etc/profile.d/conda.sh
    
    #Updating libraries
    - name: Update 
      run: sudo apt-get update
        
    #Installing Xmipp dependencies
    - name: Install python dependencies
      run:  python -m pip install --upgrade pip
        pip install scons numpy
    - name: Install dependencies
      run: sudo apt-get install -y libfftw3-dev libopenmpi-dev openmpi-bin libhdf5-dev python3-numpy python3-dev libtiff5-dev unzip libsqlite3-dev default-jdk git cmake
        

    
    # Installing Scipion
    - name: Install Scipion with dependencies
      working-directory: ${{ github.workspace }}/../
      run: |
        sudo apt-get install -y gcc-10 g++-10 libopenmpi-dev make && \
        eval "$(${{ github.workspace }}/../miniconda/bin/conda shell.bash hook)" && \
        pip3 install --user scipion-installer && \
        python3 -m scipioninstaller -conda -noXmipp -noAsk ${{ github.workspace }}/../scipion3
        
     #Cloning Xmipp 
    - name: Cloning Xmipp
      working-directory: ${{ github.workspace }}/../scipion3
      run: git clone https://github.com/I2PC/xmipp.git xmipp-bundle 


    # Check out the repository in the pull request
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        
    #Installing Xmipp
    - name: Compile Xmipp
      working-directory: ${{ github.workspace }}/../scipion3/xmipp-bundle
      run:  /../../scipion3/scipio3 run ./xmipp noAsk
            
    # Install plugin from the pull request using the Scipion3 installp command
    - name: Install plugin from pull request
      working-directory: ${{ github.workspace }}
      run: |
        # Install the repository from the pull request
        ${{ github.workspace }}/../scipion/scipion3 installp -p . --devel
